// Copyright (C) 2021 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
// Qt-Security score:significant

// this file was generated by the generate.ts script

#ifndef QLANGUAGESERVERGEN_P_H
#define QLANGUAGESERVERGEN_P_H

//
//  W A R N I N G
//  -------------
//
// This file is not part of the Qt API.  It exists purely as an
// implementation detail.  This header file may change from version to
// version without notice, or even be removed.
//
// We mean it.
//

#include <QtLanguageServer/qtlanguageserverglobal.h>
#include <QtLanguageServer/private/qlanguageserverspec_p.h>
#include <QtLanguageServer/private/qlanguageserverbase_p.h>

#include <memory>
#include <functional>

QT_BEGIN_NAMESPACE

namespace QLspSpecification {

class ProtocolGenPrivate;

class Q_LANGUAGESERVER_EXPORT ProtocolGen : public ProtocolBase
{
protected:
    ProtocolGen(std::unique_ptr<ProtocolGenPrivate> &&p);
public:
    ~ProtocolGen();

    // Requests
    void requestCallHierarchyIncomingCalls(
            const CallHierarchyIncomingCallsParams &,
            std::function<
                    void(const std::variant<QList<CallHierarchyIncomingCall>, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerCallHierarchyIncomingCallsRequestHandler(
            const std::function<
                    void(const QByteArray &, const CallHierarchyIncomingCallsParams &,
                         LSPPartialResponse<
                                 std::variant<QList<CallHierarchyIncomingCall>, std::nullptr_t>,
                                 QList<CallHierarchyIncomingCall>> &&)> &handler);
    void requestCallHierarchyOutgoingCalls(
            const CallHierarchyOutgoingCallsParams &,
            std::function<
                    void(const std::variant<QList<CallHierarchyOutgoingCall>, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerCallHierarchyOutgoingCallsRequestHandler(
            const std::function<
                    void(const QByteArray &, const CallHierarchyOutgoingCallsParams &,
                         LSPPartialResponse<
                                 std::variant<QList<CallHierarchyOutgoingCall>, std::nullptr_t>,
                                 QList<CallHierarchyOutgoingCall>> &&)> &handler);
    void requestRegistration(
            const RegistrationParams &, std::function<void()> responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerRegistrationRequestHandler(
            const std::function<void(const QByteArray &, const RegistrationParams &,
                                     LSPResponse<std::nullptr_t> &&)> &handler);
    void requestUnregistration(
            const UnregistrationParams &, std::function<void()> responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerUnregistrationRequestHandler(
            const std::function<void(const QByteArray &, const UnregistrationParams &,
                                     LSPResponse<std::nullptr_t> &&)> &handler);
    void requestCodeActionResolve(
            const CodeAction &, std::function<void(const CodeAction &)> responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerCodeActionResolveRequestHandler(
            const std::function<void(const QByteArray &, const CodeAction &,
                                     LSPResponse<CodeAction> &&)> &handler);
    void requestCodeLensRefresh(
            const std::nullptr_t &, std::function<void()> responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerCodeLensRefreshRequestHandler(
            const std::function<void(const QByteArray &, const std::nullptr_t &,
                                     LSPResponse<std::nullptr_t> &&)> &handler);
    void requestCodeLensResolve(
            const CodeLens &, std::function<void(const CodeLens &)> responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerCodeLensResolveRequestHandler(
            const std::function<void(const QByteArray &, const CodeLens &,
                                     LSPResponse<CodeLens> &&)> &handler);
    void requestCompletionItemResolve(
            const CompletionItem &, std::function<void(const CompletionItem &)> responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerCompletionItemResolveRequestHandler(
            const std::function<void(const QByteArray &, const CompletionItem &,
                                     LSPResponse<CompletionItem> &&)> &handler);
    void requestDocumentLinkResolve(
            const DocumentLink &, std::function<void(const DocumentLink &)> responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerDocumentLinkResolveRequestHandler(
            const std::function<void(const QByteArray &, const DocumentLink &,
                                     LSPResponse<DocumentLink> &&)> &handler);
    void requestInitialize(
            const InitializeParams &, std::function<void(const InitializeResult &)> responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerInitializeRequestHandler(
            const std::function<void(const QByteArray &, const InitializeParams &,
                                     LSPResponse<InitializeResult> &&)> &handler);
    void
    requestShutdown(const std::nullptr_t &, std::function<void()> responseHandler,
                    ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerShutdownRequestHandler(
            const std::function<void(const QByteArray &, const std::nullptr_t &,
                                     LSPResponse<std::nullptr_t> &&)> &handler);
    void requestCodeAction(
            const CodeActionParams &,
            std::function<void(
                    const std::variant<QList<std::variant<Command, CodeAction>>, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerCodeActionRequestHandler(
            const std::function<void(
                    const QByteArray &, const CodeActionParams &,
                    LSPPartialResponse<
                            std::variant<QList<std::variant<Command, CodeAction>>, std::nullptr_t>,
                            QList<std::variant<Command, CodeAction>>> &&)> &handler);
    void
    requestCodeLens(const CodeLensParams &,
                    std::function<void(const std::variant<QList<CodeLens>, std::nullptr_t> &)>
                            responseHandler,
                    ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerCodeLensRequestHandler(
            const std::function<
                    void(const QByteArray &, const CodeLensParams &,
                         LSPPartialResponse<std::variant<QList<CodeLens>, std::nullptr_t>,
                                            QList<CodeLens>> &&)> &handler);
    void requestColorPresentation(
            const ColorPresentationParams &,
            std::function<void(const QList<ColorPresentation> &)> responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerColorPresentationRequestHandler(
            const std::function<void(const QByteArray &, const ColorPresentationParams &,
                                     LSPPartialResponse<QList<ColorPresentation>,
                                                        QList<ColorPresentation>> &&)> &handler);
    void requestCompletion(
            const CompletionParams &,
            std::function<void(
                    const std::variant<QList<CompletionItem>, CompletionList, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerCompletionRequestHandler(
            const std::function<void(
                    const QByteArray &, const CompletionParams &,
                    LSPPartialResponse<
                            std::variant<QList<CompletionItem>, CompletionList, std::nullptr_t>,
                            std::variant<CompletionList, QList<CompletionItem>>> &&)> &handler);
    void requestDeclaration(
            const DeclarationParams &,
            std::function<void(const std::variant<Location, QList<Location>, QList<LocationLink>,
                                                  std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerDeclarationRequestHandler(
            const std::function<
                    void(const QByteArray &, const DeclarationParams &,
                         LSPPartialResponse<std::variant<Location, QList<Location>,
                                                         QList<LocationLink>, std::nullptr_t>,
                                            std::variant<QList<Location>, QList<LocationLink>>> &&)>
                    &handler);
    void requestDefinition(
            const DefinitionParams &,
            std::function<void(const std::variant<Location, QList<Location>, QList<LocationLink>,
                                                  std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerDefinitionRequestHandler(
            const std::function<
                    void(const QByteArray &, const DefinitionParams &,
                         LSPPartialResponse<std::variant<Location, QList<Location>,
                                                         QList<LocationLink>, std::nullptr_t>,
                                            std::variant<QList<Location>, QList<LocationLink>>> &&)>
                    &handler);
    void requestDocumentColor(
            const DocumentColorParams &,
            std::function<void(const QList<ColorInformation> &)> responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerDocumentColorRequestHandler(
            const std::function<void(const QByteArray &, const DocumentColorParams &,
                                     LSPPartialResponse<QList<ColorInformation>,
                                                        QList<ColorInformation>> &&)> &handler);
    void requestDocumentHighlight(
            const DocumentHighlightParams &,
            std::function<void(const std::variant<QList<DocumentHighlight>, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerDocumentHighlightRequestHandler(
            const std::function<
                    void(const QByteArray &, const DocumentHighlightParams &,
                         LSPPartialResponse<std::variant<QList<DocumentHighlight>, std::nullptr_t>,
                                            QList<DocumentHighlight>> &&)> &handler);
    void requestDocumentLink(
            const DocumentLinkParams &,
            std::function<void(const std::variant<QList<DocumentLink>, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerDocumentLinkRequestHandler(
            const std::function<
                    void(const QByteArray &, const DocumentLinkParams &,
                         LSPPartialResponse<std::variant<QList<DocumentLink>, std::nullptr_t>,
                                            QList<DocumentLink>> &&)> &handler);
    void requestDocumentSymbol(
            const DocumentSymbolParams &,
            std::function<void(const std::variant<QList<DocumentSymbol>, QList<SymbolInformation>,
                                                  std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerDocumentSymbolRequestHandler(
            const std::function<
                    void(const QByteArray &, const DocumentSymbolParams &,
                         LSPPartialResponse<std::variant<QList<DocumentSymbol>,
                                                         QList<SymbolInformation>, std::nullptr_t>,
                                            std::variant<QList<DocumentSymbol>,
                                                         QList<SymbolInformation>>> &&)> &handler);
    void requestFoldingRange(
            const FoldingRangeParams &,
            std::function<void(const std::variant<QList<FoldingRange>, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerFoldingRangeRequestHandler(
            const std::function<
                    void(const QByteArray &, const FoldingRangeParams &,
                         LSPPartialResponse<std::variant<QList<FoldingRange>, std::nullptr_t>,
                                            QList<FoldingRange>> &&)> &handler);
    void requestDocumentFormatting(
            const DocumentFormattingParams &,
            std::function<void(const std::variant<QList<TextEdit>, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerDocumentFormattingRequestHandler(
            const std::function<void(const QByteArray &, const DocumentFormattingParams &,
                                     LSPResponse<std::variant<QList<TextEdit>, std::nullptr_t>> &&)>
                    &handler);
    void
    requestHover(const HoverParams &,
                 std::function<void(const std::variant<Hover, std::nullptr_t> &)> responseHandler,
                 ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerHoverRequestHandler(
            const std::function<void(const QByteArray &, const HoverParams &,
                                     LSPResponse<std::variant<Hover, std::nullptr_t>> &&)>
                    &handler);
    void requestImplementation(
            const ImplementationParams &,
            std::function<void(const std::variant<Location, QList<Location>, QList<LocationLink>,
                                                  std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerImplementationRequestHandler(
            const std::function<
                    void(const QByteArray &, const ImplementationParams &,
                         LSPPartialResponse<std::variant<Location, QList<Location>,
                                                         QList<LocationLink>, std::nullptr_t>,
                                            std::variant<QList<Location>, QList<LocationLink>>> &&)>
                    &handler);
    void requestLinkedEditingRange(
            const LinkedEditingRangeParams &,
            std::function<void(const std::variant<LinkedEditingRanges, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerLinkedEditingRangeRequestHandler(
            const std::function<void(
                    const QByteArray &, const LinkedEditingRangeParams &,
                    LSPResponse<std::variant<LinkedEditingRanges, std::nullptr_t>> &&)> &handler);
    void
    requestMoniker(const MonikerParams &,
                   std::function<void(const std::variant<QList<Moniker>, std::nullptr_t> &)>
                           responseHandler,
                   ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerMonikerRequestHandler(
            const std::function<void(
                    const QByteArray &, const MonikerParams &,
                    LSPPartialResponse<std::variant<QList<Moniker>, std::nullptr_t>, QList<Moniker>>
                            &&)> &handler);
    void requestDocumentOnTypeFormatting(
            const DocumentOnTypeFormattingParams &,
            std::function<void(const std::variant<QList<TextEdit>, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerDocumentOnTypeFormattingRequestHandler(
            const std::function<void(const QByteArray &, const DocumentOnTypeFormattingParams &,
                                     LSPResponse<std::variant<QList<TextEdit>, std::nullptr_t>> &&)>
                    &handler);
    void requestCallHierarchyPrepare(
            const CallHierarchyPrepareParams &,
            std::function<void(const std::variant<QList<CallHierarchyItem>, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerCallHierarchyPrepareRequestHandler(
            const std::function<
                    void(const QByteArray &, const CallHierarchyPrepareParams &,
                         LSPResponse<std::variant<QList<CallHierarchyItem>, std::nullptr_t>> &&)>
                    &handler);
    void requestPrepareRename(
            const PrepareRenameParams &,
            std::function<void(const std::variant<Range, RangePlaceHolder, DefaultBehaviorStruct,
                                                  std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerPrepareRenameRequestHandler(
            const std::function<
                    void(const QByteArray &, const PrepareRenameParams &,
                         LSPResponse<std::variant<Range, RangePlaceHolder, DefaultBehaviorStruct,
                                                  std::nullptr_t>> &&)> &handler);
    void requestDocumentRangeFormatting(
            const DocumentRangeFormattingParams &,
            std::function<void(const std::variant<QList<TextEdit>, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerDocumentRangeFormattingRequestHandler(
            const std::function<void(const QByteArray &, const DocumentRangeFormattingParams &,
                                     LSPResponse<std::variant<QList<TextEdit>, std::nullptr_t>> &&)>
                    &handler);
    void requestReference(
            const ReferenceParams &,
            std::function<void(const std::variant<QList<Location>, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerReferenceRequestHandler(
            const std::function<
                    void(const QByteArray &, const ReferenceParams &,
                         LSPPartialResponse<std::variant<QList<Location>, std::nullptr_t>,
                                            QList<Location>> &&)> &handler);
    void
    requestRename(const RenameParams &,
                  std::function<void(const std::variant<WorkspaceEdit, std::nullptr_t> &)>
                          responseHandler,
                  ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerRenameRequestHandler(
            const std::function<void(const QByteArray &, const RenameParams &,
                                     LSPResponse<std::variant<WorkspaceEdit, std::nullptr_t>> &&)>
                    &handler);
    void requestSelectionRange(
            const SelectionRangeParams &,
            std::function<void(const std::variant<QList<SelectionRange>, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerSelectionRangeRequestHandler(
            const std::function<
                    void(const QByteArray &, const SelectionRangeParams &,
                         LSPPartialResponse<std::variant<QList<SelectionRange>, std::nullptr_t>,
                                            QList<SelectionRange>> &&)> &handler);
    void requestSemanticTokens(
            const SemanticTokensParams &,
            std::function<void(const std::variant<SemanticTokens, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerSemanticTokensRequestHandler(
            const std::function<
                    void(const QByteArray &, const SemanticTokensParams &,
                         LSPPartialResponse<std::variant<SemanticTokens, std::nullptr_t>,
                                            SemanticTokensPartialResult> &&)> &handler);
    void requestSemanticTokensDelta(
            const SemanticTokensDeltaParams &,
            std::function<
                    void(const std::variant<SemanticTokens, SemanticTokensDelta, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerSemanticTokensDeltaRequestHandler(
            const std::function<
                    void(const QByteArray &, const SemanticTokensDeltaParams &,
                         LSPPartialResponse<
                                 std::variant<SemanticTokens, SemanticTokensDelta, std::nullptr_t>,
                                 SemanticTokensDeltaPartialResult> &&)> &handler);
    void requestSemanticTokensRange(
            const SemanticTokensRangeParams &,
            std::function<void(const std::variant<SemanticTokens, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerSemanticTokensRangeRequestHandler(
            const std::function<
                    void(const QByteArray &, const SemanticTokensRangeParams &,
                         LSPPartialResponse<std::variant<SemanticTokens, std::nullptr_t>,
                                            SemanticTokensPartialResult> &&)> &handler);
    void requestRequestingARefreshOfAllSemanticTokens(
            const std::nullptr_t &, std::function<void()> responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerRequestingARefreshOfAllSemanticTokensRequestHandler(
            const std::function<void(const QByteArray &, const std::nullptr_t &,
                                     LSPResponse<std::nullptr_t> &&)> &handler);
    void requestSignatureHelp(
            const SignatureHelpParams &,
            std::function<void(const std::variant<SignatureHelp, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerSignatureHelpRequestHandler(
            const std::function<void(const QByteArray &, const SignatureHelpParams &,
                                     LSPResponse<std::variant<SignatureHelp, std::nullptr_t>> &&)>
                    &handler);
    void requestTypeDefinition(
            const TypeDefinitionParams &,
            std::function<void(const std::variant<Location, QList<Location>, QList<LocationLink>,
                                                  std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerTypeDefinitionRequestHandler(
            const std::function<
                    void(const QByteArray &, const TypeDefinitionParams &,
                         LSPPartialResponse<std::variant<Location, QList<Location>,
                                                         QList<LocationLink>, std::nullptr_t>,
                                            std::variant<QList<Location>, QList<LocationLink>>> &&)>
                    &handler);
    void requestWillSaveTextDocument(
            const WillSaveTextDocumentParams &,
            std::function<void(const std::variant<QList<TextEdit>, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerWillSaveTextDocumentRequestHandler(
            const std::function<void(const QByteArray &, const WillSaveTextDocumentParams &,
                                     LSPResponse<std::variant<QList<TextEdit>, std::nullptr_t>> &&)>
                    &handler);
    void requestShowDocument(
            const ShowDocumentParams &,
            std::function<void(const ShowDocumentResult &)> responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerShowDocumentRequestHandler(
            const std::function<void(const QByteArray &, const ShowDocumentParams &,
                                     LSPResponse<ShowDocumentResult> &&)> &handler);
    void requestShowMessageRequest(
            const ShowMessageRequestParams &,
            std::function<void(const std::variant<MessageActionItem, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerShowMessageRequestRequestHandler(
            const std::function<void(
                    const QByteArray &, const ShowMessageRequestParams &,
                    LSPResponse<std::variant<MessageActionItem, std::nullptr_t>> &&)> &handler);
    void requestWorkDoneProgressCreate(
            const WorkDoneProgressCreateParams &, std::function<void()> responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerWorkDoneProgressCreateRequestHandler(
            const std::function<void(const QByteArray &, const WorkDoneProgressCreateParams &,
                                     LSPResponse<std::nullptr_t> &&)> &handler);
    void requestApplyWorkspaceEdit(
            const ApplyWorkspaceEditParams &,
            std::function<void(const ApplyWorkspaceEditResponse &)> responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerApplyWorkspaceEditRequestHandler(
            const std::function<void(const QByteArray &, const ApplyWorkspaceEditParams &,
                                     LSPResponse<ApplyWorkspaceEditResponse> &&)> &handler);
    void requestConfiguration(
            const ConfigurationParams &,
            std::function<void(const QList<QJsonValue> &)> responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerConfigurationRequestHandler(
            const std::function<void(const QByteArray &, const ConfigurationParams &,
                                     LSPResponse<QList<QJsonValue>> &&)> &handler);
    void requestExecuteCommand(
            const ExecuteCommandParams &,
            std::function<void(const std::variant<QJsonValue, std::nullptr_t> &)> responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerExecuteCommandRequestHandler(
            const std::function<void(const QByteArray &, const ExecuteCommandParams &,
                                     LSPResponse<std::variant<QJsonValue, std::nullptr_t>> &&)>
                    &handler);
    void requestWorkspaceSymbol(
            const WorkspaceSymbolParams &,
            std::function<void(const std::variant<QList<SymbolInformation>, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerWorkspaceSymbolRequestHandler(
            const std::function<
                    void(const QByteArray &, const WorkspaceSymbolParams &,
                         LSPPartialResponse<std::variant<QList<SymbolInformation>, std::nullptr_t>,
                                            QList<SymbolInformation>> &&)> &handler);
    void requestCreateFiles(
            const CreateFilesParams &,
            std::function<void(const std::variant<WorkspaceEdit, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerCreateFilesRequestHandler(
            const std::function<void(const QByteArray &, const CreateFilesParams &,
                                     LSPResponse<std::variant<WorkspaceEdit, std::nullptr_t>> &&)>
                    &handler);
    void requestDeleteFiles(
            const DeleteFilesParams &,
            std::function<void(const std::variant<WorkspaceEdit, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerDeleteFilesRequestHandler(
            const std::function<void(const QByteArray &, const DeleteFilesParams &,
                                     LSPResponse<std::variant<WorkspaceEdit, std::nullptr_t>> &&)>
                    &handler);
    void requestRenameFiles(
            const RenameFilesParams &,
            std::function<void(const std::variant<WorkspaceEdit, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerRenameFilesRequestHandler(
            const std::function<void(const QByteArray &, const RenameFilesParams &,
                                     LSPResponse<std::variant<WorkspaceEdit, std::nullptr_t>> &&)>
                    &handler);
    void requestWorkspaceWorkspaceFolders(
            const std::nullptr_t &,
            std::function<void(const std::variant<QList<WorkspaceFolder>, std::nullptr_t> &)>
                    responseHandler,
            ResponseErrorHandler errorHandler = &ProtocolBase::defaultResponseErrorHandler);
    void registerWorkspaceWorkspaceFoldersRequestHandler(
            const std::function<
                    void(const QByteArray &, const std::nullptr_t &,
                         LSPResponse<std::variant<QList<WorkspaceFolder>, std::nullptr_t>> &&)>
                    &handler);

    // Notifications
    void registerCancelNotificationHandler(
            const std::function<void(const QByteArray &, const CancelParams &)> &handler);
    void notifyCancel(const CancelParams &params);
    void registerExitNotificationHandler(
            const std::function<void(const QByteArray &, const std::nullptr_t &)> &handler);
    void notifyExit(const std::nullptr_t &params);
    void registerInitializedNotificationHandler(
            const std::function<void(const QByteArray &, const InitializedParams &)> &handler);
    void notifyInitialized(const InitializedParams &params);
    void registerLogTraceNotificationHandler(
            const std::function<void(const QByteArray &, const LogTraceParams &)> &handler);
    void notifyLogTrace(const LogTraceParams &params);
    void registerProgressNotificationHandler(
            const std::function<void(const QByteArray &, const ProgressParams &)> &handler);
    void notifyProgress(const ProgressParams &params);
    void registerSetTraceNotificationHandler(
            const std::function<void(const QByteArray &, const SetTraceParams &)> &handler);
    void notifySetTrace(const SetTraceParams &params);
    void registerTelemetryEventNotificationHandler(
            const std::function<void(const QByteArray &, const QJsonObject &)> &handler);
    void notifyTelemetryEvent(const QJsonObject &params);
    void registerDidChangeTextDocumentNotificationHandler(
            const std::function<void(const QByteArray &, const DidChangeTextDocumentParams &)>
                    &handler);
    void notifyDidChangeTextDocument(const DidChangeTextDocumentParams &params);
    void registerDidCloseTextDocumentNotificationHandler(
            const std::function<void(const QByteArray &, const DidCloseTextDocumentParams &)>
                    &handler);
    void notifyDidCloseTextDocument(const DidCloseTextDocumentParams &params);
    void registerDidOpenTextDocumentNotificationHandler(
            const std::function<void(const QByteArray &, const DidOpenTextDocumentParams &)>
                    &handler);
    void notifyDidOpenTextDocument(const DidOpenTextDocumentParams &params);
    void registerDidSaveTextDocumentNotificationHandler(
            const std::function<void(const QByteArray &, const DidSaveTextDocumentParams &)>
                    &handler);
    void notifyDidSaveTextDocument(const DidSaveTextDocumentParams &params);
    void registerPublishDiagnosticsNotificationHandler(
            const std::function<void(const QByteArray &, const PublishDiagnosticsParams &)>
                    &handler);
    void notifyPublishDiagnostics(const PublishDiagnosticsParams &params);
    void registerWillSaveTextDocumentNotificationHandler(
            const std::function<void(const QByteArray &, const WillSaveTextDocumentParams &)>
                    &handler);
    void notifyWillSaveTextDocument(const WillSaveTextDocumentParams &params);
    void registerLogMessageNotificationHandler(
            const std::function<void(const QByteArray &, const LogMessageParams &)> &handler);
    void notifyLogMessage(const LogMessageParams &params);
    void registerShowMessageNotificationHandler(
            const std::function<void(const QByteArray &, const ShowMessageParams &)> &handler);
    void notifyShowMessage(const ShowMessageParams &params);
    void registerWorkDoneProgressCancelNotificationHandler(
            const std::function<void(const QByteArray &, const WorkDoneProgressCancelParams &)>
                    &handler);
    void notifyWorkDoneProgressCancel(const WorkDoneProgressCancelParams &params);
    void registerDidChangeConfigurationNotificationHandler(
            const std::function<void(const QByteArray &, const DidChangeConfigurationParams &)>
                    &handler);
    void notifyDidChangeConfiguration(const DidChangeConfigurationParams &params);
    void registerDidChangeWatchedFilesNotificationHandler(
            const std::function<void(const QByteArray &, const DidChangeWatchedFilesParams &)>
                    &handler);
    void notifyDidChangeWatchedFiles(const DidChangeWatchedFilesParams &params);
    void registerDidChangeWorkspaceFoldersNotificationHandler(
            const std::function<void(const QByteArray &, const DidChangeWorkspaceFoldersParams &)>
                    &handler);
    void notifyDidChangeWorkspaceFolders(const DidChangeWorkspaceFoldersParams &params);
    void registerCreateFilesNotificationHandler(
            const std::function<void(const QByteArray &, const CreateFilesParams &)> &handler);
    void notifyCreateFiles(const CreateFilesParams &params);
    void registerDeleteFilesNotificationHandler(
            const std::function<void(const QByteArray &, const DeleteFilesParams &)> &handler);
    void notifyDeleteFiles(const DeleteFilesParams &params);
    void registerRenameFilesNotificationHandler(
            const std::function<void(const QByteArray &, const RenameFilesParams &)> &handler);
    void notifyRenameFiles(const RenameFilesParams &params);

private:
    Q_DISABLE_COPY(ProtocolGen)
    Q_DECLARE_PRIVATE(ProtocolGen)
};

} // namespace QLspSpecification

QT_END_NAMESPACE

#endif // QLANGUAGESERVER_P_H
