// Copyright (C) 2021 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
// Qt-Security score:significant

// this file was generated by the generate.ts script

#ifndef QLANGUAGESERVERSPEC_P_H
#define QLANGUAGESERVERSPEC_P_H

//
//  W A R N I N G
//  -------------
//
// This file is not part of the Qt API.  It exists purely as an
// implementation detail.  This header file may change from version to
// version without notice, or even be removed.
//
// We mean it.
//

#include <QtLanguageServer/qtlanguageserverglobal.h>
#include <QtLanguageServer/private/qlanguageserverspectypes_p.h>

QT_BEGIN_NAMESPACE

namespace QLspSpecification {
namespace ClientCapabilitiesInfo {
constexpr auto TextDocumentCodeActionResolveSupport = "textDocument.codeAction.resolveSupport";
using TextDocumentCodeActionResolveSupportType = QJsonObject;
constexpr auto WorkspaceCodeLens = "workspace.codeLens";
using WorkspaceCodeLensType = CodeLensWorkspaceClientCapabilities;
constexpr auto GeneralRegularExpressions = "general.regularExpressions";
using GeneralRegularExpressionsType = RegularExpressionsClientCapabilities;
constexpr auto TextDocumentCodeAction = "textDocument.codeAction";
using TextDocumentCodeActionType = CodeActionClientCapabilities;
constexpr auto TextDocumentCodeLens = "textDocument.codeLens";
using TextDocumentCodeLensType = CodeLensClientCapabilities;
constexpr auto TextDocumentCompletion = "textDocument.completion";
using TextDocumentCompletionType = CompletionClientCapabilities;
constexpr auto TextDocumentDeclaration = "textDocument.declaration";
using TextDocumentDeclarationType = DeclarationClientCapabilities;
constexpr auto TextDocumentDefinition = "textDocument.definition";
using TextDocumentDefinitionType = DefinitionClientCapabilities;
constexpr auto TextDocumentSynchronizationDidSave = "textDocument.synchronization.didSave";
using TextDocumentSynchronizationDidSaveType = bool;
constexpr auto TextDocumentColorProvider = "textDocument.colorProvider";
using TextDocumentColorProviderType = DocumentColorClientCapabilities;
constexpr auto TextDocumentDocumentHighlight = "textDocument.documentHighlight";
using TextDocumentDocumentHighlightType = DocumentHighlightClientCapabilities;
constexpr auto TextDocumentDocumentLink = "textDocument.documentLink";
using TextDocumentDocumentLinkType = DocumentLinkClientCapabilities;
constexpr auto TextDocumentDocumentSymbol = "textDocument.documentSymbol";
using TextDocumentDocumentSymbolType = DocumentSymbolClientCapabilities;
constexpr auto TextDocumentFoldingRange = "textDocument.foldingRange";
using TextDocumentFoldingRangeType = FoldingRangeClientCapabilities;
constexpr auto TextDocumentFormatting = "textDocument.formatting";
using TextDocumentFormattingType = DocumentFormattingClientCapabilities;
constexpr auto TextDocumentHover = "textDocument.hover";
using TextDocumentHoverType = HoverClientCapabilities;
constexpr auto TextDocumentImplementation = "textDocument.implementation";
using TextDocumentImplementationType = ImplementationClientCapabilities;
constexpr auto TextDocumentOnTypeFormatting = "textDocument.onTypeFormatting";
using TextDocumentOnTypeFormattingType = DocumentOnTypeFormattingClientCapabilities;
constexpr auto TextDocumentCallHierarchy = "textDocument.callHierarchy";
using TextDocumentCallHierarchyType = CallHierarchyClientCapabilities;
constexpr auto TextDocumentPublishDiagnostics = "textDocument.publishDiagnostics";
using TextDocumentPublishDiagnosticsType = PublishDiagnosticsClientCapabilities;
constexpr auto TextDocumentRangeFormatting = "textDocument.rangeFormatting";
using TextDocumentRangeFormattingType = DocumentRangeFormattingClientCapabilities;
constexpr auto TextDocumentReferences = "textDocument.references";
using TextDocumentReferencesType = ReferenceClientCapabilities;
constexpr auto TextDocumentRename = "textDocument.rename";
using TextDocumentRenameType = RenameClientCapabilities;
constexpr auto TextDocumentSelectionRange = "textDocument.selectionRange";
using TextDocumentSelectionRangeType = SelectionRangeClientCapabilities;
constexpr auto TextDocumentSemanticTokens = "textDocument.semanticTokens";
using TextDocumentSemanticTokensType = SemanticTokensClientCapabilities;
constexpr auto WorkspaceSemanticTokens = "workspace.semanticTokens";
using WorkspaceSemanticTokensType = SemanticTokensWorkspaceClientCapabilities;
constexpr auto TextDocumentSignatureHelp = "textDocument.signatureHelp";
using TextDocumentSignatureHelpType = SignatureHelpClientCapabilities;
constexpr auto TextDocumentSynchronizationDynamicRegistration =
        "textDocument.synchronization.dynamicRegistration";
using TextDocumentSynchronizationDynamicRegistrationType = bool;
constexpr auto TextDocumentTypeDefinition = "textDocument.typeDefinition";
using TextDocumentTypeDefinitionType = TypeDefinitionClientCapabilities;
constexpr auto TextDocumentSynchronizationWillSave = "textDocument.synchronization.willSave";
using TextDocumentSynchronizationWillSaveType = bool;
constexpr auto TextDocumentSynchronizationWillSaveWaitUntil =
        "textDocument.synchronization.willSaveWaitUntil";
using TextDocumentSynchronizationWillSaveWaitUntilType = bool;
constexpr auto WindowShowDocument = "window.showDocument";
using WindowShowDocumentType = ShowDocumentClientCapabilities;
constexpr auto WindowShowMessage = "window.showMessage";
using WindowShowMessageType = ShowMessageRequestClientCapabilities;
constexpr auto WorkspaceWorkspaceEdit = "workspace.workspaceEdit";
using WorkspaceWorkspaceEditType = WorkspaceEditClientCapabilities;
constexpr auto WorkspaceApplyEdit = "workspace.applyEdit";
using WorkspaceApplyEditType = bool;
constexpr auto WorkspaceConfiguration = "workspace.configuration";
using WorkspaceConfigurationType = bool;
constexpr auto WorkspaceDidChangeConfiguration = "workspace.didChangeConfiguration";
using WorkspaceDidChangeConfigurationType = DidChangeConfigurationClientCapabilities;
constexpr auto WorkspaceDidChangeWatchedFiles = "workspace.didChangeWatchedFiles";
using WorkspaceDidChangeWatchedFilesType = DidChangeWatchedFilesClientCapabilities;
constexpr auto WorkspaceFileOperationsDidCreate = "workspace.fileOperations.didCreate";
using WorkspaceFileOperationsDidCreateType = bool;
constexpr auto WorkspaceFileOperationsDidDelete = "workspace.fileOperations.didDelete";
using WorkspaceFileOperationsDidDeleteType = bool;
constexpr auto WorkspaceFileOperationsDidRename = "workspace.fileOperations.didRename";
using WorkspaceFileOperationsDidRenameType = bool;
constexpr auto WorkspaceExecuteCommand = "workspace.executeCommand";
using WorkspaceExecuteCommandType = ExecuteCommandClientCapabilities;
constexpr auto WorkspaceSymbol = "workspace.symbol";
using WorkspaceSymbolType = WorkspaceSymbolClientCapabilities;
constexpr auto WorkspaceFileOperationsWillCreate = "workspace.fileOperations.willCreate";
using WorkspaceFileOperationsWillCreateType = bool;
constexpr auto WorkspaceFileOperationsWillDelete = "workspace.fileOperations.willDelete";
using WorkspaceFileOperationsWillDeleteType = bool;
constexpr auto WorkspaceFileOperationsWillRename = "workspace.fileOperations.willRename";
using WorkspaceFileOperationsWillRenameType = bool;
constexpr auto WorkspaceWorkspaceFolders = "workspace.workspaceFolders";
using WorkspaceWorkspaceFoldersType = bool;
} // namespace ClientCapabilitiesInfo

namespace ServerCapabilitiesInfo {
constexpr auto CodeActionProvider = "codeActionProvider";
using CodeActionProviderType = std::variant<bool, CodeActionOptions>;
constexpr auto CodeLensProvider = "codeLensProvider";
using CodeLensProviderType = CodeLensOptions;
constexpr auto CompletionProvider = "completionProvider";
using CompletionProviderType = CompletionOptions;
constexpr auto DeclarationProvider = "declarationProvider";
using DeclarationProviderType =
        std::variant<bool, DeclarationOptions, DeclarationRegistrationOptions>;
constexpr auto DefinitionProvider = "definitionProvider";
using DefinitionProviderType = std::variant<bool, DefinitionOptions>;
constexpr auto TextDocumentSyncSave = "textDocumentSync.save";
using TextDocumentSyncSaveType = std::variant<bool, SaveOptions>;
constexpr auto ColorProvider = "colorProvider";
using ColorProviderType =
        std::variant<bool, DocumentColorOptions, DocumentColorRegistrationOptions>;
constexpr auto DocumentHighlightProvider = "documentHighlightProvider";
using DocumentHighlightProviderType = std::variant<bool, DocumentHighlightOptions>;
constexpr auto DocumentLinkProvider = "documentLinkProvider";
using DocumentLinkProviderType = DocumentLinkOptions;
constexpr auto DocumentSymbolProvider = "documentSymbolProvider";
using DocumentSymbolProviderType = std::variant<bool, DocumentSymbolOptions>;
constexpr auto FoldingRangeProvider = "foldingRangeProvider";
using FoldingRangeProviderType =
        std::variant<bool, FoldingRangeOptions, FoldingRangeRegistrationOptions>;
constexpr auto DocumentFormattingProvider = "documentFormattingProvider";
using DocumentFormattingProviderType = std::variant<bool, DocumentFormattingOptions>;
constexpr auto HoverProvider = "hoverProvider";
using HoverProviderType = std::variant<bool, HoverOptions>;
constexpr auto ImplementationProvider = "implementationProvider";
using ImplementationProviderType =
        std::variant<bool, ImplementationOptions, ImplementationRegistrationOptions>;
constexpr auto LinkedEditingRangeProvider = "linkedEditingRangeProvider";
using LinkedEditingRangeProviderType =
        std::variant<bool, LinkedEditingRangeOptions, LinkedEditingRangeRegistrationOptions>;
constexpr auto MonikerProvider = "monikerProvider";
using MonikerProviderType = std::variant<bool, MonikerOptions, MonikerRegistrationOptions>;
constexpr auto DocumentOnTypeFormattingProvider = "documentOnTypeFormattingProvider";
using DocumentOnTypeFormattingProviderType = DocumentOnTypeFormattingOptions;
constexpr auto CallHierarchyProvider = "callHierarchyProvider";
using CallHierarchyProviderType =
        std::variant<bool, CallHierarchyOptions, CallHierarchyRegistrationOptions>;
constexpr auto DocumentRangeFormattingProvider = "documentRangeFormattingProvider";
using DocumentRangeFormattingProviderType = std::variant<bool, DocumentRangeFormattingOptions>;
constexpr auto ReferencesProvider = "referencesProvider";
using ReferencesProviderType = std::variant<bool, ReferenceOptions>;
constexpr auto RenameProvider = "renameProvider";
using RenameProviderType = std::variant<bool, RenameOptions>;
constexpr auto SelectionRangeProvider = "selectionRangeProvider";
using SelectionRangeProviderType =
        std::variant<bool, SelectionRangeOptions, SelectionRangeRegistrationOptions>;
constexpr auto SemanticTokensProvider = "semanticTokensProvider";
using SemanticTokensProviderType =
        std::variant<SemanticTokensOptions, SemanticTokensRegistrationOptions>;
constexpr auto SignatureHelpProvider = "signatureHelpProvider";
using SignatureHelpProviderType = SignatureHelpOptions;
constexpr auto TextDocumentSync = "textDocumentSync";
using TextDocumentSyncType = std::variant<TextDocumentSyncKind, TextDocumentSyncOptions>;
constexpr auto TypeDefinitionProvider = "typeDefinitionProvider";
using TypeDefinitionProviderType =
        std::variant<bool, TypeDefinitionOptions, TypeDefinitionRegistrationOptions>;
constexpr auto TextDocumentSyncWillSave = "textDocumentSync.willSave";
using TextDocumentSyncWillSaveType = bool;
constexpr auto TextDocumentSyncWillSaveWaitUntil = "textDocumentSync.willSaveWaitUntil";
using TextDocumentSyncWillSaveWaitUntilType = bool;
constexpr auto WorkspaceFileOperationsDidCreate = "workspace.fileOperations.didCreate";
using WorkspaceFileOperationsDidCreateType = FileOperationRegistrationOptions;
constexpr auto WorkspaceFileOperationsDidDelete = "workspace.fileOperations.didDelete";
using WorkspaceFileOperationsDidDeleteType = FileOperationRegistrationOptions;
constexpr auto WorkspaceFileOperationsDidRename = "workspace.fileOperations.didRename";
using WorkspaceFileOperationsDidRenameType = FileOperationRegistrationOptions;
constexpr auto ExecuteCommandProvider = "executeCommandProvider";
using ExecuteCommandProviderType = ExecuteCommandOptions;
constexpr auto WorkspaceSymbolProvider = "workspaceSymbolProvider";
using WorkspaceSymbolProviderType = std::variant<bool, WorkspaceSymbolOptions>;
constexpr auto WorkspaceFileOperationsWillCreate = "workspace.fileOperations.willCreate";
using WorkspaceFileOperationsWillCreateType = FileOperationRegistrationOptions;
constexpr auto WorkspaceFileOperationsWillDelete = "workspace.fileOperations.willDelete";
using WorkspaceFileOperationsWillDeleteType = FileOperationRegistrationOptions;
constexpr auto WorkspaceFileOperationsWillRename = "workspace.fileOperations.willRename";
using WorkspaceFileOperationsWillRenameType = FileOperationRegistrationOptions;
constexpr auto WorkspaceWorkspaceFolders = "workspace.workspaceFolders";
using WorkspaceWorkspaceFoldersType = WorkspaceFoldersServerCapabilities;
} // namespace ServerCapabilitiesInfo

namespace Requests {
constexpr auto CallHierarchyIncomingCallsMethod = "callHierarchy/incomingCalls";
using CallHierarchyIncomingCallsParamsType = CallHierarchyIncomingCallsParams;
constexpr auto CallHierarchyOutgoingCallsMethod = "callHierarchy/outgoingCalls";
using CallHierarchyOutgoingCallsParamsType = CallHierarchyOutgoingCallsParams;
constexpr auto RegistrationMethod = "client/registerCapability";
using RegistrationParamsType = RegistrationParams;
constexpr auto UnregistrationMethod = "client/unregisterCapability";
using UnregistrationParamsType = UnregistrationParams;
constexpr auto CodeActionResolveMethod = "codeAction/resolve";
using CodeActionResolveParamsType = CodeAction;
constexpr auto CodeLensRefreshMethod = "workspace/codeLens/refresh";
using CodeLensRefreshParamsType = std::nullptr_t;
constexpr auto CodeLensResolveMethod = "codeLens/resolve";
using CodeLensResolveParamsType = CodeLens;
constexpr auto CompletionItemResolveMethod = "completionItem/resolve";
using CompletionItemResolveParamsType = CompletionItem;
constexpr auto DocumentLinkResolveMethod = "documentLink/resolve";
using DocumentLinkResolveParamsType = DocumentLink;
constexpr auto InitializeMethod = "initialize";
using InitializeParamsType = InitializeParams;
constexpr auto ShutdownMethod = "shutdown";
using ShutdownParamsType = std::nullptr_t;
constexpr auto CodeActionMethod = "textDocument/codeAction";
using CodeActionParamsType = CodeActionParams;
constexpr auto CodeLensMethod = "textDocument/codeLens";
using CodeLensParamsType = CodeLensParams;
constexpr auto ColorPresentationMethod = "textDocument/colorPresentation";
using ColorPresentationParamsType = ColorPresentationParams;
constexpr auto CompletionMethod = "textDocument/completion";
using CompletionParamsType = CompletionParams;
constexpr auto DeclarationMethod = "textDocument/declaration";
using DeclarationParamsType = DeclarationParams;
constexpr auto DefinitionMethod = "textDocument/definition";
using DefinitionParamsType = DefinitionParams;
constexpr auto DocumentColorMethod = "textDocument/documentColor";
using DocumentColorParamsType = DocumentColorParams;
constexpr auto DocumentHighlightMethod = "textDocument/documentHighlight";
using DocumentHighlightParamsType = DocumentHighlightParams;
constexpr auto DocumentLinkMethod = "textDocument/documentLink";
using DocumentLinkParamsType = DocumentLinkParams;
constexpr auto DocumentSymbolMethod = "textDocument/documentSymbol";
using DocumentSymbolParamsType = DocumentSymbolParams;
constexpr auto FoldingRangeMethod = "textDocument/foldingRange";
using FoldingRangeParamsType = FoldingRangeParams;
constexpr auto DocumentFormattingMethod = "textDocument/formatting";
using DocumentFormattingParamsType = DocumentFormattingParams;
constexpr auto HoverMethod = "textDocument/hover";
using HoverParamsType = HoverParams;
constexpr auto ImplementationMethod = "textDocument/implementation";
using ImplementationParamsType = ImplementationParams;
constexpr auto LinkedEditingRangeMethod = "textDocument/linkedEditingRange";
using LinkedEditingRangeParamsType = LinkedEditingRangeParams;
constexpr auto MonikerMethod = "textDocument/moniker";
using MonikerParamsType = MonikerParams;
constexpr auto DocumentOnTypeFormattingMethod = "textDocument/onTypeFormatting";
using DocumentOnTypeFormattingParamsType = DocumentOnTypeFormattingParams;
constexpr auto CallHierarchyPrepareMethod = "textDocument/prepareCallHierarchy";
using CallHierarchyPrepareParamsType = CallHierarchyPrepareParams;
constexpr auto PrepareRenameMethod = "textDocument/prepareRename";
using PrepareRenameParamsType = PrepareRenameParams;
constexpr auto DocumentRangeFormattingMethod = "textDocument/rangeFormatting";
using DocumentRangeFormattingParamsType = DocumentRangeFormattingParams;
constexpr auto ReferenceMethod = "textDocument/references";
using ReferenceParamsType = ReferenceParams;
constexpr auto RenameMethod = "textDocument/rename";
using RenameParamsType = RenameParams;
constexpr auto SelectionRangeMethod = "textDocument/selectionRange";
using SelectionRangeParamsType = SelectionRangeParams;
constexpr auto SemanticTokensMethod = "textDocument/semanticTokens/full";
using SemanticTokensParamsType = SemanticTokensParams;
constexpr auto SemanticTokensDeltaMethod = "textDocument/semanticTokens/full/delta";
using SemanticTokensDeltaParamsType = SemanticTokensDeltaParams;
constexpr auto SemanticTokensRangeMethod = "textDocument/semanticTokens/range";
using SemanticTokensRangeParamsType = SemanticTokensRangeParams;
constexpr auto RequestingARefreshOfAllSemanticTokensMethod = "workspace/semanticTokens/refresh";
using RequestingARefreshOfAllSemanticTokensParamsType = std::nullptr_t;
constexpr auto SignatureHelpMethod = "textDocument/signatureHelp";
using SignatureHelpParamsType = SignatureHelpParams;
constexpr auto TypeDefinitionMethod = "textDocument/typeDefinition";
using TypeDefinitionParamsType = TypeDefinitionParams;
constexpr auto WillSaveTextDocumentMethod = "textDocument/willSaveWaitUntil";
using WillSaveTextDocumentParamsType = WillSaveTextDocumentParams;
constexpr auto ShowDocumentMethod = "window/showDocument";
using ShowDocumentParamsType = ShowDocumentParams;
constexpr auto ShowMessageRequestMethod = "window/showMessageRequest";
using ShowMessageRequestParamsType = ShowMessageRequestParams;
constexpr auto WorkDoneProgressCreateMethod = "window/workDoneProgress/create";
using WorkDoneProgressCreateParamsType = WorkDoneProgressCreateParams;
constexpr auto ApplyWorkspaceEditMethod = "workspace/applyEdit";
using ApplyWorkspaceEditParamsType = ApplyWorkspaceEditParams;
constexpr auto ConfigurationMethod = "workspace/configuration";
using ConfigurationParamsType = ConfigurationParams;
constexpr auto ExecuteCommandMethod = "workspace/executeCommand";
using ExecuteCommandParamsType = ExecuteCommandParams;
constexpr auto WorkspaceSymbolMethod = "workspace/symbol";
using WorkspaceSymbolParamsType = WorkspaceSymbolParams;
constexpr auto CreateFilesMethod = "workspace/willCreateFiles";
using CreateFilesParamsType = CreateFilesParams;
constexpr auto DeleteFilesMethod = "workspace/willDeleteFiles";
using DeleteFilesParamsType = DeleteFilesParams;
constexpr auto RenameFilesMethod = "workspace/willRenameFiles";
using RenameFilesParamsType = RenameFilesParams;
constexpr auto WorkspaceWorkspaceFoldersMethod = "workspace/workspaceFolders";
using WorkspaceWorkspaceFoldersParamsType = std::nullptr_t;
}

namespace Responses {
using CallHierarchyIncomingCallsResultType =
        std::variant<QList<CallHierarchyIncomingCall>, std::nullptr_t>;
using CallHierarchyIncomingCallsPartialResultType = QList<CallHierarchyIncomingCall>;
using CallHierarchyIncomingCallsResponseType =
        LSPPartialResponse<CallHierarchyIncomingCallsResultType,
                           CallHierarchyIncomingCallsPartialResultType>;
using CallHierarchyOutgoingCallsResultType =
        std::variant<QList<CallHierarchyOutgoingCall>, std::nullptr_t>;
using CallHierarchyOutgoingCallsPartialResultType = QList<CallHierarchyOutgoingCall>;
using CallHierarchyOutgoingCallsResponseType =
        LSPPartialResponse<CallHierarchyOutgoingCallsResultType,
                           CallHierarchyOutgoingCallsPartialResultType>;
using RegistrationResultType = std::nullptr_t;
using RegistrationResponseType = LSPResponse<RegistrationResultType>;
using UnregistrationResultType = std::nullptr_t;
using UnregistrationResponseType = LSPResponse<UnregistrationResultType>;
using CodeActionResolveResultType = CodeAction;
using CodeActionResolveResponseType = LSPResponse<CodeActionResolveResultType>;
using CodeLensRefreshResultType = std::nullptr_t;
using CodeLensRefreshResponseType = LSPResponse<CodeLensRefreshResultType>;
using CodeLensResolveResultType = CodeLens;
using CodeLensResolveResponseType = LSPResponse<CodeLensResolveResultType>;
using CompletionItemResolveResultType = CompletionItem;
using CompletionItemResolveResponseType = LSPResponse<CompletionItemResolveResultType>;
using DocumentLinkResolveResultType = DocumentLink;
using DocumentLinkResolveResponseType = LSPResponse<DocumentLinkResolveResultType>;
using InitializeResultType = InitializeResult;
using InitializeResponseType = LSPResponse<InitializeResultType>;
using ShutdownResultType = std::nullptr_t;
using ShutdownResponseType = LSPResponse<ShutdownResultType>;
using CodeActionResultType = std::variant<QList<std::variant<Command, CodeAction>>, std::nullptr_t>;
using CodeActionPartialResultType = QList<std::variant<Command, CodeAction>>;
using CodeActionResponseType =
        LSPPartialResponse<CodeActionResultType, CodeActionPartialResultType>;
using CodeLensResultType = std::variant<QList<CodeLens>, std::nullptr_t>;
using CodeLensPartialResultType = QList<CodeLens>;
using CodeLensResponseType = LSPPartialResponse<CodeLensResultType, CodeLensPartialResultType>;
using ColorPresentationResultType = QList<ColorPresentation>;
using ColorPresentationPartialResultType = QList<ColorPresentation>;
using ColorPresentationResponseType =
        LSPPartialResponse<ColorPresentationResultType, ColorPresentationPartialResultType>;
using CompletionResultType = std::variant<QList<CompletionItem>, CompletionList, std::nullptr_t>;
using CompletionPartialResultType = std::variant<CompletionList, QList<CompletionItem>>;
using CompletionResponseType =
        LSPPartialResponse<CompletionResultType, CompletionPartialResultType>;
using DeclarationResultType =
        std::variant<Location, QList<Location>, QList<LocationLink>, std::nullptr_t>;
using DeclarationPartialResultType = std::variant<QList<Location>, QList<LocationLink>>;
using DeclarationResponseType =
        LSPPartialResponse<DeclarationResultType, DeclarationPartialResultType>;
using DefinitionResultType =
        std::variant<Location, QList<Location>, QList<LocationLink>, std::nullptr_t>;
using DefinitionPartialResultType = std::variant<QList<Location>, QList<LocationLink>>;
using DefinitionResponseType =
        LSPPartialResponse<DefinitionResultType, DefinitionPartialResultType>;
using DocumentColorResultType = QList<ColorInformation>;
using DocumentColorPartialResultType = QList<ColorInformation>;
using DocumentColorResponseType =
        LSPPartialResponse<DocumentColorResultType, DocumentColorPartialResultType>;
using DocumentHighlightResultType = std::variant<QList<DocumentHighlight>, std::nullptr_t>;
using DocumentHighlightPartialResultType = QList<DocumentHighlight>;
using DocumentHighlightResponseType =
        LSPPartialResponse<DocumentHighlightResultType, DocumentHighlightPartialResultType>;
using DocumentLinkResultType = std::variant<QList<DocumentLink>, std::nullptr_t>;
using DocumentLinkPartialResultType = QList<DocumentLink>;
using DocumentLinkResponseType =
        LSPPartialResponse<DocumentLinkResultType, DocumentLinkPartialResultType>;
using DocumentSymbolResultType =
        std::variant<QList<DocumentSymbol>, QList<SymbolInformation>, std::nullptr_t>;
using DocumentSymbolPartialResultType =
        std::variant<QList<DocumentSymbol>, QList<SymbolInformation>>;
using DocumentSymbolResponseType =
        LSPPartialResponse<DocumentSymbolResultType, DocumentSymbolPartialResultType>;
using FoldingRangeResultType = std::variant<QList<FoldingRange>, std::nullptr_t>;
using FoldingRangePartialResultType = QList<FoldingRange>;
using FoldingRangeResponseType =
        LSPPartialResponse<FoldingRangeResultType, FoldingRangePartialResultType>;
using DocumentFormattingResultType = std::variant<QList<TextEdit>, std::nullptr_t>;
using DocumentFormattingResponseType = LSPResponse<DocumentFormattingResultType>;
using HoverResultType = std::variant<Hover, std::nullptr_t>;
using HoverResponseType = LSPResponse<HoverResultType>;
using ImplementationResultType =
        std::variant<Location, QList<Location>, QList<LocationLink>, std::nullptr_t>;
using ImplementationPartialResultType = std::variant<QList<Location>, QList<LocationLink>>;
using ImplementationResponseType =
        LSPPartialResponse<ImplementationResultType, ImplementationPartialResultType>;
using LinkedEditingRangeResultType = std::variant<LinkedEditingRanges, std::nullptr_t>;
using LinkedEditingRangeResponseType = LSPResponse<LinkedEditingRangeResultType>;
using MonikerResultType = std::variant<QList<Moniker>, std::nullptr_t>;
using MonikerPartialResultType = QList<Moniker>;
using MonikerResponseType = LSPPartialResponse<MonikerResultType, MonikerPartialResultType>;
using DocumentOnTypeFormattingResultType = std::variant<QList<TextEdit>, std::nullptr_t>;
using DocumentOnTypeFormattingResponseType = LSPResponse<DocumentOnTypeFormattingResultType>;
using CallHierarchyPrepareResultType = std::variant<QList<CallHierarchyItem>, std::nullptr_t>;
using CallHierarchyPrepareResponseType = LSPResponse<CallHierarchyPrepareResultType>;
using PrepareRenameResultType =
        std::variant<Range, RangePlaceHolder, DefaultBehaviorStruct, std::nullptr_t>;
using PrepareRenameResponseType = LSPResponse<PrepareRenameResultType>;
using DocumentRangeFormattingResultType = std::variant<QList<TextEdit>, std::nullptr_t>;
using DocumentRangeFormattingResponseType = LSPResponse<DocumentRangeFormattingResultType>;
using ReferenceResultType = std::variant<QList<Location>, std::nullptr_t>;
using ReferencePartialResultType = QList<Location>;
using ReferenceResponseType = LSPPartialResponse<ReferenceResultType, ReferencePartialResultType>;
using RenameResultType = std::variant<WorkspaceEdit, std::nullptr_t>;
using RenameResponseType = LSPResponse<RenameResultType>;
using SelectionRangeResultType = std::variant<QList<SelectionRange>, std::nullptr_t>;
using SelectionRangePartialResultType = QList<SelectionRange>;
using SelectionRangeResponseType =
        LSPPartialResponse<SelectionRangeResultType, SelectionRangePartialResultType>;
using SemanticTokensResultType = std::variant<SemanticTokens, std::nullptr_t>;
using SemanticTokensPartialResultType = SemanticTokensPartialResult;
using SemanticTokensResponseType =
        LSPPartialResponse<SemanticTokensResultType, SemanticTokensPartialResultType>;
using SemanticTokensDeltaResultType =
        std::variant<SemanticTokens, SemanticTokensDelta, std::nullptr_t>;
using SemanticTokensDeltaPartialResultType = SemanticTokensDeltaPartialResult;
using SemanticTokensDeltaResponseType =
        LSPPartialResponse<SemanticTokensDeltaResultType, SemanticTokensDeltaPartialResultType>;
using SemanticTokensRangeResultType = std::variant<SemanticTokens, std::nullptr_t>;
using SemanticTokensRangePartialResultType = SemanticTokensPartialResult;
using SemanticTokensRangeResponseType =
        LSPPartialResponse<SemanticTokensRangeResultType, SemanticTokensRangePartialResultType>;
using RequestingARefreshOfAllSemanticTokensResultType = std::nullptr_t;
using RequestingARefreshOfAllSemanticTokensResponseType =
        LSPResponse<RequestingARefreshOfAllSemanticTokensResultType>;
using SignatureHelpResultType = std::variant<SignatureHelp, std::nullptr_t>;
using SignatureHelpResponseType = LSPResponse<SignatureHelpResultType>;
using TypeDefinitionResultType =
        std::variant<Location, QList<Location>, QList<LocationLink>, std::nullptr_t>;
using TypeDefinitionPartialResultType = std::variant<QList<Location>, QList<LocationLink>>;
using TypeDefinitionResponseType =
        LSPPartialResponse<TypeDefinitionResultType, TypeDefinitionPartialResultType>;
using WillSaveTextDocumentResultType = std::variant<QList<TextEdit>, std::nullptr_t>;
using WillSaveTextDocumentResponseType = LSPResponse<WillSaveTextDocumentResultType>;
using ShowDocumentResultType = ShowDocumentResult;
using ShowDocumentResponseType = LSPResponse<ShowDocumentResultType>;
using ShowMessageRequestResultType = std::variant<MessageActionItem, std::nullptr_t>;
using ShowMessageRequestResponseType = LSPResponse<ShowMessageRequestResultType>;
using WorkDoneProgressCreateResultType = std::nullptr_t;
using WorkDoneProgressCreateResponseType = LSPResponse<WorkDoneProgressCreateResultType>;
using ApplyWorkspaceEditResultType = ApplyWorkspaceEditResponse;
using ApplyWorkspaceEditResponseType = LSPResponse<ApplyWorkspaceEditResultType>;
using ConfigurationResultType = QList<QJsonValue>;
using ConfigurationResponseType = LSPResponse<ConfigurationResultType>;
using ExecuteCommandResultType = std::variant<QJsonValue, std::nullptr_t>;
using ExecuteCommandResponseType = LSPResponse<ExecuteCommandResultType>;
using WorkspaceSymbolResultType = std::variant<QList<SymbolInformation>, std::nullptr_t>;
using WorkspaceSymbolPartialResultType = QList<SymbolInformation>;
using WorkspaceSymbolResponseType =
        LSPPartialResponse<WorkspaceSymbolResultType, WorkspaceSymbolPartialResultType>;
using CreateFilesResultType = std::variant<WorkspaceEdit, std::nullptr_t>;
using CreateFilesResponseType = LSPResponse<CreateFilesResultType>;
using DeleteFilesResultType = std::variant<WorkspaceEdit, std::nullptr_t>;
using DeleteFilesResponseType = LSPResponse<DeleteFilesResultType>;
using RenameFilesResultType = std::variant<WorkspaceEdit, std::nullptr_t>;
using RenameFilesResponseType = LSPResponse<RenameFilesResultType>;
using WorkspaceWorkspaceFoldersResultType = std::variant<QList<WorkspaceFolder>, std::nullptr_t>;
using WorkspaceWorkspaceFoldersResponseType = LSPResponse<WorkspaceWorkspaceFoldersResultType>;
}

namespace Notifications {
constexpr auto CancelMethod = "$/cancelRequest";
using CancelParamsType = CancelParams;
constexpr auto ExitMethod = "exit";
using ExitParamsType = std::nullptr_t;
constexpr auto InitializedMethod = "initialized";
using InitializedParamsType = InitializedParams;
constexpr auto LogTraceMethod = "$/logTrace";
using LogTraceParamsType = LogTraceParams;
constexpr auto ProgressMethod = "$/progress";
using ProgressParamsType = ProgressParams;
constexpr auto SetTraceMethod = "$/setTrace";
using SetTraceParamsType = SetTraceParams;
constexpr auto TelemetryEventMethod = "telemetry/event";
using TelemetryEventParamsType = QJsonObject;
constexpr auto DidChangeTextDocumentMethod = "textDocument/didChange";
using DidChangeTextDocumentParamsType = DidChangeTextDocumentParams;
constexpr auto DidCloseTextDocumentMethod = "textDocument/didClose";
using DidCloseTextDocumentParamsType = DidCloseTextDocumentParams;
constexpr auto DidOpenTextDocumentMethod = "textDocument/didOpen";
using DidOpenTextDocumentParamsType = DidOpenTextDocumentParams;
constexpr auto DidSaveTextDocumentMethod = "textDocument/didSave";
using DidSaveTextDocumentParamsType = DidSaveTextDocumentParams;
constexpr auto PublishDiagnosticsMethod = "textDocument/publishDiagnostics";
using PublishDiagnosticsParamsType = PublishDiagnosticsParams;
constexpr auto WillSaveTextDocumentMethod = "textDocument/willSave";
using WillSaveTextDocumentParamsType = WillSaveTextDocumentParams;
constexpr auto LogMessageMethod = "window/logMessage";
using LogMessageParamsType = LogMessageParams;
constexpr auto ShowMessageMethod = "window/showMessage";
using ShowMessageParamsType = ShowMessageParams;
constexpr auto WorkDoneProgressCancelMethod = "window/workDoneProgress/cancel";
using WorkDoneProgressCancelParamsType = WorkDoneProgressCancelParams;
constexpr auto DidChangeConfigurationMethod = "workspace/didChangeConfiguration";
using DidChangeConfigurationParamsType = DidChangeConfigurationParams;
constexpr auto DidChangeWatchedFilesMethod = "workspace/didChangeWatchedFiles";
using DidChangeWatchedFilesParamsType = DidChangeWatchedFilesParams;
constexpr auto DidChangeWorkspaceFoldersMethod = "workspace/didChangeWorkspaceFolders";
using DidChangeWorkspaceFoldersParamsType = DidChangeWorkspaceFoldersParams;
constexpr auto CreateFilesMethod = "workspace/didCreateFiles";
using CreateFilesParamsType = CreateFilesParams;
constexpr auto DeleteFilesMethod = "workspace/didDeleteFiles";
using DeleteFilesParamsType = DeleteFilesParams;
constexpr auto RenameFilesMethod = "workspace/didRenameFiles";
using RenameFilesParamsType = RenameFilesParams;
}

using RequestParams = std::variant<
        CallHierarchyIncomingCallsParams, CallHierarchyOutgoingCallsParams, RegistrationParams,
        UnregistrationParams, CodeAction, std::nullptr_t, CodeLens, CompletionItem, DocumentLink,
        InitializeParams, CodeActionParams, CodeLensParams, ColorPresentationParams,
        CompletionParams, DeclarationParams, DefinitionParams, DocumentColorParams,
        DocumentHighlightParams, DocumentLinkParams, DocumentSymbolParams, FoldingRangeParams,
        DocumentFormattingParams, HoverParams, ImplementationParams, LinkedEditingRangeParams,
        MonikerParams, DocumentOnTypeFormattingParams, CallHierarchyPrepareParams,
        PrepareRenameParams, DocumentRangeFormattingParams, ReferenceParams, RenameParams,
        SelectionRangeParams, SemanticTokensParams, SemanticTokensDeltaParams,
        SemanticTokensRangeParams, SignatureHelpParams, TypeDefinitionParams,
        WillSaveTextDocumentParams, ShowDocumentParams, ShowMessageRequestParams,
        WorkDoneProgressCreateParams, ApplyWorkspaceEditParams, ConfigurationParams,
        ExecuteCommandParams, WorkspaceSymbolParams, CreateFilesParams, DeleteFilesParams,
        RenameFilesParams, QJsonValue>;
using NotificationParams =
        std::variant<CancelParams, std::nullptr_t, InitializedParams, LogTraceParams,
                     ProgressParams, SetTraceParams, QJsonObject, DidChangeTextDocumentParams,
                     DidCloseTextDocumentParams, DidOpenTextDocumentParams,
                     DidSaveTextDocumentParams, PublishDiagnosticsParams,
                     WillSaveTextDocumentParams, LogMessageParams, ShowMessageParams,
                     WorkDoneProgressCancelParams, DidChangeConfigurationParams,
                     DidChangeWatchedFilesParams, DidChangeWorkspaceFoldersParams,
                     CreateFilesParams, DeleteFilesParams, RenameFilesParams, QJsonValue>;

} // namespace QLspSpecification

QT_END_NAMESPACE

#endif // QLANGUAGESERVERSPEC_P_H
